### ISSUE TITLE
大佬,似乎无法正常使用?

### ISSUE THREAD

**Issue by 23233** [chenyue404/IntentInterceptor#1]
如题,打开之后,测试网页跳转到app 无法拦截下intent呢? 大佬是否正常使用?

**Comment by chenyue404** [comment]
> 如题,打开之后,测试网页跳转到app 无法拦截下intent呢? 大佬是否正常使用?

https://github.com/chenyue404/ActivityLog 这个可以看参数，https://github.com/chenyue404/IntentFilter 这个可以拦截跳转。
